<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Folder Include="Objeto\" />
    <Folder Include="Repositorios\" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="MySqlConnector" Version="2.6.2" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\SALONBELLEZA.CORE\SALONBELLEZA.CORE.csproj" />
    <ProjectReference Include="..\SALONBELLEZA.SHARED\SALONBELLEZA.SHARED.csproj" />
    <ProjectReference Include="..\SALONBELLEZA.TEST\SALONBELLEZA.TEST.csproj" />
  </ItemGroup>

</Project>
